###todos
GET http://localhost:8080/users
### filtrado
GET http://localhost:8080/users?role=emp
###con id
GET http://localhost:8080/users/1
### nuevo usuario
POST http://localhost:8080/users

Content-Type: application/json

{
    "name": "Pepe",
    "age": 20,
    "email": "pepe@gmail.com",
    "role": "emp"
}

